### ISSUE TITLE
Immutable is set always to true

### ISSUE THREAD

**Issue by damianopetrungaro** [lorenzomar/zend-hydrator-utilities#1]
You must set the immutable flag to true as optional.
Or remove the possibility to pass the params for set it.

https://github.com/lorenzomar/zend-hydrator-utilities/blob/master/src/Strategy/DateTimeFormatterStrategy.php#L46

PS
boolean as params is not so elegant.
You should read the article by martin fowler about it.

http://martinfowler.com/bliki/FlagArgument.html

**Comment by lorenzomar** [comment]
Fixed
